{% set version = "3.3.2" %}

package:
    name: pyamg
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/p/pyamg/pyamg-3.3.2.tar.gz
    sha256: ccebb1b0379cab87b493e8e5fc5388c89b9738445ae10e5adfebe6f48078ca27

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - numpy x.x
        - zlib  # [linux]
        - setuptools
    run:
        - python
        - numpy x.x
        - scipy
        - zlib  # [linux]
        - pytest

test:
    requires:
        - pytest
    imports:
        - pyamg
        - pyamg.amg_core._amg_core
        - pyamg.aggregation
        - pyamg.aggregation.tests
        - pyamg.amg_core
        - pyamg.classical
        - pyamg.classical.tests
        - pyamg.gallery
        - pyamg.gallery.tests
        - pyamg.krylov
        - pyamg.krylov.tests
        - pyamg.relaxation
        - pyamg.relaxation.tests
        - pyamg.tests
        - pyamg.util
        - pyamg.util.tests
        - pyamg.vis
        - pyamg.vis.tests


about:
    home: http://www.pyamg.org/
    license: MIT
    license_file: LICENSE.txt
    summary: "Algebraic Multigrid Solvers in Python"
    description: |
      PyAMG is a library of Algebraic Multigrid (AMG) solvers with a convenient
      Python interface.
    doc_url: https://pypi.python.org/pypi/pyamg
    doc_source_url: https://github.com/pyamg/pyamg
    dev_url: https://github.com/pyamg/pyamg

extra:
  recipe-maintainers:
    - jakevdp
