{% set name = "pyamg" %}
{% set version = "5.2.1" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f449d934224e503401ee72cd2eece1a29d893b7abe35f62a44d52ba831198efa

build:
    number: 0
    script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vv

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - python
        - pip
        - pybind11 >=2.8.0
        - setuptools >=42
        - setuptools-scm >=7.0.0
        - toml
        - wheel
    run:
        - python
        - numpy
        - scipy >=1.11.0

test:
    imports:
        - pyamg
    requires:
        - pip
        - pytest
    commands:
        - pip check
        - python -c "import pyamg; pyamg.test(verbose=True)"

about:
    home: https://github.com/pyamg/pyamg
    license: MIT
    license_file: LICENSE.txt
    license_family: MIT
    summary: Algebraic Multigrid Solvers in Python
    description: |
        PyAMG is a library of Algebraic Multigrid (AMG) solvers with a convenient
        Python interface.
    doc_url: https://pypi.python.org/pypi/pyamg
    doc_source_url: https://github.com/pyamg/pyamg
    dev_url: https://github.com/pyamg/pyamg

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
