{% set version = "3.3.2" %}

package:
    name: pyamg
    version: {{ version }}

source:
    url: https://pypi.python.org/packages/68/b4/dec7df885abef3c92914ab7cb20efb8528f17764e91f9deb24d9cc029c80/pyamg-3.3.2.tar.gz
    md5: 73d2bccb182e3895ce2d07c65f8fe27e

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - numpy x.x
        - zlib  # [linux]
        - setuptools
    run:
        - python
        - numpy x.x
        - scipy
        - zlib  # [linux]
        - pytest

test:
    requires:
        - pytest
    imports:
        - pyamg

about:
    home: http://www.pyamg.org/
    license: MIT
    license_file: LICENSE.txt
    summary: "Algebraic Multigrid Solvers in Python"

extra:
  recipe-maintainers:
    - jakevdp
