{% set name = "pyamg" %}
{% set version = "4.2.2" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9adac5a94c04bacb58942702895d454199bb7492a886eeb9d311dd88d83a0fa1

build:
    number: 0
    script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    skip: True   # [win and vc<14]

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - python
        - numpy
        - pybind11 >=2.2
        - setuptools
        - pip
    run:
        - python
        - {{ pin_compatible("numpy") }}
        - scipy >=0.12.0

test:
    requires:
        - pytest
    imports:
        - pyamg

about:
    home: https://github.com/pyamg/pyamg
    license: MIT
    license_file: LICENSE.txt
    summary: "Algebraic Multigrid Solvers in Python"
    description: |
      PyAMG is a library of Algebraic Multigrid (AMG) solvers with a convenient
      Python interface.
    doc_url: https://pypi.python.org/pypi/pyamg
    doc_source_url: https://github.com/pyamg/pyamg
    dev_url: https://github.com/pyamg/pyamg

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
