travis:
  secure:
    BINSTAR_TOKEN: c0uMsnm3NdkP1RRQZZdRiPsoCU25TsqbZ2/KgTz5guVqpunpdvMdCZGhlj/iz7VSa/zbH6u84itJD/lznsYaJNdmIe1DtDda2JYYylqqtCVqRmzs6G5L2ptij8/16A/yM+dShWZRmq0tqaC9ACMnYaxTFLo4Lv6KLTgGkYvmBDEdG5m09FKvQlolIfYU38V8QXXBpEGKEiBZ+L+iBa5/N0E5++RmvuWKCyFC50WFdTWA1Zr6TAVoOK18S79whuPGdixLJhOxM95ta+XGC2m+uV6KAV0kem/i8iNH0IGTozV23odjhRL9xheNMdSkCVbrKv6VWBq6X5I79sm7CrIXY7rOxjOS7gXmZ3Jp0CeBbL0uwMOpHC3kyUhZIqJXLVbEQaa5ndDfMo72aTt1XuebIONp1peVOE1nd1gb1y8OaPfjw7M3z+DIGZ+mdIyB7Y+SvBC85gBA243W257hnfFDXAm3+tOnObVXxY3mqVZoOhovWp6tdLpcdHNztmQOtARKXNkHxqBLpZpJ21wA/DTS5u+uMuSvMgp5Thfbdsjq/CWJqdGzXZGd3dHK2pkGWFzec2B4BIspuh6u1m72xrOiXncRJrZbKAsFoHNQmHO9popxwDG8O56gN25uS5vxfWSEahWftCIH7Mxd9WD+Ewk6H7Z1VmvuFEXpRNevUyO34Ro=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
