travis:
  secure:
    BINSTAR_TOKEN: OT2cXUbFn+lcFBEHAJleRxdKxTQbNycaBcB0MIW2EuFrE3RHuMUbbML3zsFAXyCkhr7jRK+12g/w4DqKAV+xmHZ3+YLzy8YZCIGUvS9dCF83EEjMM6GBn4aMRDWVbKiY+YjwFHoaiIA8u/y5fjcN1SnhBJbelyBU9e71Mft5nCAAOrGyA8axL2Bzdh0x9QGtWV6RPdAwZw6K0EBxx3ZEYhPtCnYuiVWqzsVkN+DFnwKbFtYMm5VKUs5qLWgZwwHB3uUDzQJLkhnBLLI+wDfCEsMP1Iysu9WYXiW55rqETYnL45UHUx9xohrkFPNwi80x5TbNRkGacUMsWPRT22+mDeC9vGMAb2FrZ+l4wJ+n+XlGwANG3tJcs2DzQz/t0gTjBiqj8VQDFQZq53tKUr9JkSTjo7LkYl9KNM3QcOI+ALeGg8bb9SBxsg/+0kyg5j61hLaAFH5uCkgPmeZ8DRHcHfg1Q8G3043WV3UzsM83MmhxGpOrUf76FN3eWh+3R/7a1W2vyI9+dS+neWwEMR8nfq/ATmXALoLBgTdZMPkCSnZJsG9tjcANDJMcd0/hMr/MvDgfmKCAOp3NpE2mGe0r0iEUjc8YsTGC8rNrZ5PZlxslLvBf3yPSM5K3P5RA4W2rU5BVlDdj/HGJtZ0eJMFzXz6apQki28IwkgDV6zV0F20=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
